### ISSUE TITLE
java.lang.IllegalStateException  com.salesforce.androidsdk.push.PushService.runIntentInService

### ISSUE THREAD

**Issue by harshitaahuja** [forcedotcom/SalesforceMobileSDK-Android#1690] opened 2018-05-01 08:00 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 6.0
2. Issue found in Native App or Hybrid App:Native
3. OS Version:8.0
4. Device:Sony Xperia XZ Premium (G8141),Samsung Galaxy S8 (dreamlte)

5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3397)
  at android.app.ActivityThread.-wrap18 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1780)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6938)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
Caused by: java.lang.IllegalStateException: 
  at android.app.ContextImpl.startServiceCommon (ContextImpl.java:1538)
  at android.app.ContextImpl.startService (ContextImpl.java:1484)
  at android.content.ContextWrapper.startService (ContextWrapper.java:663)
  at com.salesforce.androidsdk.push.PushService.runIntentInService (PushService.java:112)
  at com.salesforce.androidsdk.push.PushMessaging.runPushService (PushMessaging.java:164)
  at com.salesforce.androidsdk.push.PushMessaging.registerSFDCPush (PushMessaging.java:145)
  at com.salesforce.androidsdk.push.PushService$SFDCRegistrationRetryAlarmReceiver.onReceive (PushService.java:375)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3390)
```

**Comment by bhariharan** [comment] 2018-05-01 15:40
@harshitaahuja Do you have repro steps? The stack trace indicates a crash in one of the `Android OS` APIs that we can't do anything about. All we're doing is `context.startService(intent);` on a valid `intent`. Do you see this on any other device? It could be a weird corruption issue specific to that device.

**Comment by harshitaahuja** [comment] 2018-05-02 07:36
These crashes came on production live app, and it's only on 8.0 so far. It may be related to Oreo only. I am not sure about its cause.

**Comment by bhariharan** [comment] 2018-05-02 15:12
Closing this issue since the stack trace indicates a crash in an `Android OS` API and we can't reproduce it in-house.

**Comment by harshitaahuja** [comment] 2018-05-02 16:41
https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten
It may be related to not able to start service when app is in background. In that case it should be changed to job scheduler

**Comment by bhariharan** [comment] 2018-05-02 16:43
I'll take a look. Thanks.

**Comment by wmathurin** [comment] 2018-06-13 21:08
Fixed by: https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1717

**Closed by wmathurin** 2018-06-13 21:08 UTC
Labels: investigation
