### ISSUE TITLE
Session expired or Invalid when opening the app after 30 minutes

### ISSUE THREAD

**Issue by rahulrkrish91** [forcedotcom/SalesforceMobileSDK-Android#2471] opened 2023-10-11 06:34 UTC
Please fill out the following details: Logged into the app, Minimized the app and killed the app from background. Opened the app after 30 minutes. Got the following error
com.salesforce.androidsdk.mobilesync.manager.SyncManager$MobileSyncException: [{"message":"Session expired or invalid","errorCode":"INVALID_SESSION_ID"}]

1. Version of Mobile SDK Used: 11.0.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 14, 13
4. Device: Pixel 8
5. Steps to reproduce: Logged into the app, Minimized the app and killed the app from background. Opened the app after 30 minutes
6. Actual behavior: Invalid session
7. Expected Behavior: Should be able to login to the app
8. Error Log: com.salesforce.androidsdk.mobilesync.manager.SyncManager$MobileSyncException: [{"message":"Session expired or invalid","errorCode":"INVALID_SESSION_ID"}]
                                                                                                    	at com.salesforce.androidsdk.mobilesync.target.SoqlSyncDownTarget.getResponseJson(SoqlSyncDownTarget.java:178)
                                                                                                    	at com.salesforce.androidsdk.mobilesync.target.SoqlSyncDownTarget.startFetch(SoqlSyncDownTarget.java:160)
                                                                                                    	at com.salesforce.androidsdk.mobilesync.target.SoqlSyncDownTarget.startFetch(SoqlSyncDownTarget.java:154)
                                                                                                    	at com.salesforce.androidsdk.mobilesync.manager.SyncDownTask.runSync(SyncDownTask.java:55)
                                                                                                    	at com.salesforce.androidsdk.mobilesync.manager.SyncTask.run(SyncTask.java:80)

**Comment by wmathurin** [comment] 2023-10-11 21:42
What is your connected app refresh policy? Ideally it should be "Refresh token is valid until revoked". For more information see https://help.salesforce.com/s/articleView?id=sf.connected_app_manage_oauth.htm&type=5

**Comment by rahulrkrish91** [comment] 2023-10-12 05:51
@wmathurin, The issue mentioned was tested in iPhone 14 Pro Max which is running iOS 17.0.2. But things were working fine there. So should we still check on connected app refresh policy?

**Comment by rahulrkrish91** [comment] 2023-10-12 06:45
@wmathurin, The refresh token policy is set as "Refresh token is valid until revoked". We did not face this issue in sdk 9.2.1

**Comment by rahulrkrish91** [comment] 2023-11-03 10:20
Hi @wmathurin, Any info on this issue?

**Comment by wmathurin** [comment] 2023-11-10 17:52
Before we dig further, could you upgrade to the new version of Mobile SDK that was just released (11.1).

**Comment by rahulrkrish91** [comment] 2023-11-20 04:17
Hi @wmathurin , We are still facing this issue with SDK 11.1 in Android 14. We have referred the below 2 links as well
https://help.salesforce.com/s/articleView?id=000387018&type=1
https://developer.salesforce.com/forums/?id=906F000000099xAIAQ

**Comment by wmathurin** [comment] 2023-11-20 21:03
Looking at your [post](https://developer.salesforce.com/forums/?id=906F000000099xAIAQ) on developer.salesforce.com, it seems that you are able to reproduce the issue with a simple curl call. That would mean there is some configuration or server side issue instead of a Mobile SDK bug. Let's see if you get any useful answers there, I don't think there is much we can do from our side.

**Comment by rahulrkrish91** [comment] 2023-12-01 11:16
@wmathurin. We are initializing the MobileSyncSDKManager::initNative in the App class and not from a service.

**Comment by wmathurin** [comment] 2024-05-08 23:31
We recently released Mobile SDK 12.0. Could you upgrade and see if you still have the issue?

**Comment by rahulrkrish91** [comment] 2024-05-09 01:06
The issue is resolved in SDK 11.0.0. The app was working fine on real
device. It was not working in emulator.

**Comment by wmathurin** [comment] 2024-05-09 01:09
Closing - since @rahulrkrish91 reported the issue as being resolved.

**Closed by wmathurin** 2024-05-09 01:09 UTC
