### ISSUE TITLE
DBHelper: getCachedTableName() returns wrong table name during Sync

### ISSUE THREAD

**Issue by sarath-agile** [forcedotcom/SalesforceMobileSDK-Android#1211] opened 2016-08-03 07:26 UTC
Please fill out the following details:
1. Version of Mobile SDK Used: 4.2
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Android 6
4. Device:Android x86 Emulator
5. Steps to reproduce:
   `drops all the soups from the UI and starts the sync operation` 
6. Actual behavior:
   DBHelper:getCachedTableName() returns the deleted table name instead of the new one.
7. Expected Behavior:
   DBHelper:getCachedTableName() always returns the table name of the new one.
8. Error Log:

``````
08-03 12:16:15.017 28694-28694/com.example D/com.salesforce.androidsdk.smartstore.store.DBHelper: getCachedTableName() null
08-03 12:16:15.110 28694-28694/com.example D/com.salesforce.androidsdk.smartstore.store.DBHelper: getCachedTableName() TABLE_45
08-03 12:16:15.133 28694-28694/com.example D/com.salesforce.androidsdk.smartstore.store.DBHelper: getCachedTableName() TABLE_45
08-03 12:16:16.042 30694-858/com.example:sync D/com.salesforce.androidsdk.smartstore.store.DBHelper: getCachedTableName() TABLE_35
08-03 12:16:16.496 30694-858/com.example:sync D/com.salesforce.androidsdk.smartstore.store.DBHelper: getCachedTableName() TABLE_35
08-03 12:16:16.982 30694-858/com.example:sync D/com.salesforce.androidsdk.smartstore.store.DBHelper: getCachedTableName() TABLE_35


08-03 12:16:20.137 30694-885/com.example:sync E/ACRA: com.example  fatal error : error code 1: no such table: TABLE_35
                                                          net.sqlcipher.database.SQLiteException: error code 1: no such table: TABLE_35
                                                              at net.sqlcipher.database.SQLiteStatement.native_execute(Native Method)
                                                              at net.sqlcipher.database.SQLiteStatement.execute(SQLiteStatement.java:58)
                                                              at net.sqlcipher.database.SQLiteDatabase.delete(SQLiteDatabase.java:2022)
                                                              at com.salesforce.androidsdk.smartstore.store.DBHelper.delete(DBHelper.java:378)
                                                              at com.salesforce.androidsdk.smartstore.store.SmartStore.clearSoup(SmartStore.java:565)  
                                                              at com.example.soup.SoupBase.clearSoup(SoupBase.java:198)
                                                              at com.example.soup.sync.BaseLoader.clearSoup(BaseLoader.java:95)
                                                              at com.example.soup.sync.BaseLoader.reRegisterSoup(BaseLoader.java:100)
                                                              at com.example.soup.sync.ObjectsLoader.resetIfNeeded(ObjectsLoader.java:145)
                                                              at com.example.soup.sync.ObjectsLoader.syncUp(ObjectsLoader.java:44)
                                                              at com.example.soup.sync.ObjectsLoader.syncUp(ObjectsLoader.java:40)
                                                              at com.example.soup.sync.SoupSyncAdapter.doSoupsSync(SoupSyncAdapter.java:103)
                                                              at com.example.soup.sync.SoupSyncAdapter.onPerformSync(SoupSyncAdapter.java:71)
                                                              at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)```
``````

**Comment by sarath-agile** [comment] 2016-08-04 06:39
Error reproduced in sample Application.
[https://github.com/sarath-agile/SmartSyncTest](https://github.com/sarath-agile/SmartSyncTest)

**Comment by wmathurin** [comment] 2016-08-04 16:49
Thanks for sharing your sample application.

I looked at your code. The problem is that you are working from two processes.
You drop the soups from the application process but run sync from the service. 

The caches of DBHelper instance in the service are not invalidated when you drop the sources from the application.

To work around that limitation, I recommend you have the main application send and intent to the service to have it clear its memory cache after dropping all soups. DBHelper has a clearMemoryCache method.

**Comment by sarath-agile** [comment] 2016-08-09 07:21
I tried to clear the cache from the other process but which gives another error. The error is reproduced in the sample code.  
```
08-09 12:45:15.959 10710-10737/com.sarath.smartsynctest:sync E/AndroidRuntime: FATAL EXCEPTION: SyncAdapterThread-2
                                                                               Process: com.sarath.smartsynctest:sync, PID: 10710
                                                                               com.salesforce.androidsdk.smartstore.store.SmartStore$SmartStoreException: Soup: syncs_soup does not exist
                                                                                   at com.salesforce.androidsdk.smartstore.store.SmartStore.create(SmartStore.java:783)
                                                                                   at com.salesforce.androidsdk.smartstore.store.SmartStore.upsert(SmartStore.java:1064)
                                                                                   at com.salesforce.androidsdk.smartstore.store.SmartStore.upsert(SmartStore.java:1018)
                                                                                   at com.salesforce.androidsdk.smartstore.store.SmartStore.upsert(SmartStore.java:1032)
                                                                                   at com.sarath.smartsynctest.sync.SyncAdapter.onPerformSync(SyncAdapter.java:52)
                                                                                   at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
```

**Comment by wmathurin** [comment] 2016-08-11 06:51
@bhariharan didn't we have sample code illustrating background sync on Android?

**Comment by bhariharan** [comment] 2016-08-11 17:02
@wmathurin Yes we do, in `SmartSyncExplorer` [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/native/NativeSampleApps/SmartSyncExplorer/src/com/salesforce/samples/smartsyncexplorer/sync/ContactSyncAdapter.java). Unfortunately, we run into the same issue on `logout` and logging in right away. I'm working on fixing that in the sample app, by adding a `LOGOUT_COMPLETE Intent`, so that apps can react accordingly.

Possible solutions:
* Receive the `LOGOUT_COMPLETE Intent` to the `SyncAdapter` and clean memory cache.
* Tear down the `SyncAdapter` and re-initialize it on `logout` or whenever it needs to be cleaned.

**Comment by huminzhi** [comment] 2016-08-11 18:35
The issue is fixed or solved in latest build.

**Comment by bhariharan** [comment] 2016-08-11 21:16
@huminzhi This isn't resolved. I'm working on it.

**Comment by huminzhi** [comment] 2016-08-12 18:36
The issue is fixed or solved in latest build.

**Comment by huminzhi** [comment] 2016-08-12 19:36
@bhariharan something wrong with my auto script since this bug was at first labeled as investigation.. now I fixed the script, should be good now.. sorry for the trouble.

**Comment by bhariharan** [comment] 2017-04-21 01:21
This is fixed on the `dev` branch and will be a part of our upcoming release.

**Closed by bhariharan** 2017-04-21 01:21 UTC
Labels: bug
