### ISSUE TITLE
SyncManager.syncUp() doesnot have different fieldlist for SyncUpTarget.createOnServer() and SyncUpTarget.updateOnServer()

### ISSUE THREAD

**Issue by sarath-agile** [forcedotcom/SalesforceMobileSDK-Android#1169] opened 2016-06-23 04:06 UTC
The SyncManager syncUp functionality does not have the provision to have separate fieldlist for create and update.

It is creating issues when there is fields which are not allowed on update but still required when creating the object.

**Comment by huminzhi** [comment] 2017-02-06 19:35
The issue is fixed in build:MobileSDK.Android.5.1
Please try to reproduce again and see if it still exists. Thank you!

**Closed** 2017-02-06 19:43 UTC
Labels: backlog
