### ISSUE TITLE
Login Activity getting mixed up between apps

### ISSUE THREAD

**Issue by smithaaron** [forcedotcom/SalesforceMobileSDK-Android#1940] opened 2019-06-27 16:12 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 7.1.2
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Android 9
4. Device: pixel 2XL
5. Steps to reproduce: 
I'm currently trying to implement authentication in my app using the salesforce SDK. I have a test app where I test out various features, then I have my production app. Both of these are using the Salesforce SDK.
The test app has a custom LoginActivity which extends AccountAuthenticatorActivity. The prod app doesn't define a LoginActivity.

6. Actual behavior:
When login is invoked in the production app, sometimes the SDK tries to launch the LoginActivity from the test app. 

7. Expected Behavior:
SDK instance form one app should not be aware of the other app.

8. Error Log:
2019-06-27 16:57:33.817 27848-28089/com.my.prod.app W/Binder: Binder call failed.
    java.lang.SecurityException: Permission Denial: starting Intent { flg=0x20000000 pkg=com.my.test.app cmp=com.my.test.app/com.my.test.app.auth.LoginActvity (has extras) } from ProcessRecord{211a0cb 27848:com.my.prod.app/u0a399} (pid=27848, uid=10399) not exported from uid 10397
        at android.os.Parcel.createException(Parcel.java:1950)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3756)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1669)
        at android.app.Activity.startActivityForResult(Activity.java:4587)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:657)
        at android.app.Activity.startActivityForResult(Activity.java:4545)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:644)
        at android.app.Activity.startActivity(Activity.java:4906)
        at android.app.Activity.startActivity(Activity.java:4874)
        at android.accounts.AccountManager$AmsTask$Response.onResult(AccountManager.java:2337)
        at android.accounts.IAccountManagerResponse$Stub.onTransact(IAccountManagerResponse.java:60)
        at android.os.Binder.execTransact(Binder.java:731)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1779)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:725)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:551)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1156)
        at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:490)

**Comment by wmathurin** [comment] 2019-06-27 19:51
It's a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1893.
Make sure each app uses a different account_type. For more details, see [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1893#issuecomment-486291125)

**Closed by wmathurin** 2019-06-27 19:51 UTC
