### ISSUE TITLE
Back button not working on Android 6 the first time

### ISSUE THREAD

**Issue by marta0483** [forcedotcom/SalesforceMobileSDK-Android#1077] opened 2016-03-07 12:24 UTC
We are using Salesforce SDK 4.1.0 for hybrid applications (in our case local instead of remote) on Android 6 platform. When the application is launched the first time, the back button doesn´t work. After closing and opening again, it works correctly. On Android 5 it doesn't happen.﻿

**Comment by wmathurin** [comment] 2016-03-12 00:05
Probably a cordova w/ android 6 bug.
Are you registering a backbutton handler in your application (https://cordova.apache.org/docs/en/5.0.0/cordova/events/events.backbutton.html)?

**Comment by huminzhi** [comment] 2016-05-06 20:23
@marta0483 Is this issue resolved?

**Comment by marta0483** [comment] 2016-07-11 08:40
@huminzhi No. It is still happening. 
@wmathurin. We have registered a backbutton handler in our application, but it doesn´t work the first time you enter in the app.

**Comment by helenren** [comment] 2016-07-11 23:24
Tried with our latest version 4.2.0 against 6.0, it works fine for me. @marta0483, our 4.2.0 version is released, could you please have a try against 4.2.0? Thanks.

**Comment by marta0483** [comment] 2016-07-12 11:44
Hello for your quick response @helenren.
We have tried to update to 4.2.0 release, but the problem is still happening. Also it has involved to change the method for authenticate in Android (we are using the Salesforce SDK cordova plugin) and our application is going to be delivered shortly. For this reason, we will keep on 4.1.1 version. Thanks.

**Comment by kchitalia** [comment] 2016-07-20 18:53
@marta0483 We will officially support Android N in our 5.0 release.

**Comment by huminzhi** [comment] 2016-08-03 20:27
@marta0483 I am a bit confused by this statement: "When the application is launched the first time, the back button doesn´t work. After closing and opening again, it works correctly",   by "closing and opening again", do you mean background/foreground app or kill/resume app, if it's the later, I don't see what's the differences between "first launched" and "closing and opening again"... Thanks to reply!

**Comment by marta0483** [comment] 2016-08-04 07:47
Hello @huminzhi. After installing and opening the application the first time, I kill it and then open again. The second time is when the back button works properly. 
I have tried with other devices that have the same Android version, and it seems that only happens in a Nexus 5...

**Comment by huminzhi** [comment] 2016-08-10 15:34
@marta0483 just curious if you have tried it on another Nexus 5? Want to rule out device hardware issue..

**Comment by huminzhi** [comment] 2016-08-16 17:11
@marta0483 actually I am able to reproduce this now .. we will work on it soon

**Comment by huminzhi** [comment] 2016-08-24 21:58
@marta0483 Sorry that I saw the issue once and thought I can reproduce it, but after that I am not able to reproduce it any more..

**Comment by bhariharan** [comment] 2016-12-03 21:11
This is fixed in the latest version of `Cordova` - `6.1.0`, which will be in our upcoming `Mobile SDK 5.0` release.

**Closed by bhariharan** 2016-12-03 21:11 UTC
Labels: investigation
