### ISSUE TITLE
Application Error message box shown when connection interrupted - should use error page

### ISSUE THREAD

**Issue by alsocalledchris** [forcedotcom/SalesforceMobileSDK-Android#1683] opened 2018-04-26 08:02 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 6.1
2. Issue found in Native App or Hybrid App: Hybrid
3. OS Version: Android Oreo
4. Device: Samsung S8
5. Steps to reproduce:

- Have PIN setup on device and Org
- Open the App, enter correct PIN
- Put phone into aeroplane mode

6. Actual behavior: 

- App throws 'Application error' message box with 'web page not available' page shown behind
Message box says: 'Application Error: net::ER_CONNECTION_ABORTED(https://{pod}.salesforce.com/secur/frontdoor.jsp?&sid={sessionId})'
App shows: 
'Web page not available
The web page at {web page} could not be loaded because: ERR_CONNECTION_ABORTED'

7. Expected Behavior:
Error page referenced in bootconfig.json should be shown with generic message. It should not show the Session ID to the screen. (Error page is shown successfully if the App is loaded when there is no internet connection to start with.)

8. Error Log: NA

**Comment by bhariharan** [comment] 2018-04-26 20:26
@alsocalledchris Just to clarify, this is on `SalesforceDroidGapActivity`, right? Post-login?

**Comment by alsocalledchris** [comment] 2018-04-28 13:36
@bhariharan not sure about SalesforceDroidGapActivity, but it is post login as it has the Session ID and is using it to log the user into the Org.

**Comment by wmathurin** [comment] 2021-05-06 23:41
This looks like a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1712

**Closed by wmathurin** 2021-05-06 23:41 UTC
Labels: bug
