### ISSUE TITLE
Clear Location Field won't pass Null but Keeps the existing Values in Location Fields.

### ISSUE THREAD

**Issue by NewTech2000** [forcedotcom/SalesforceMobileSDK-Android#2475] opened 2023-10-17 06:29 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 10.1.1 and 10.2.0
2. Issue found in Native App or Hybrid App: Hybrid app
3. OS Version:  12.0.0
4. Device:  All Android devices
5. Steps to reproduce:  When clearing Location fields, assign the Null value to an already existing value.
6. Actual behavior:  When clearing the Location field value should be empty when passing null instead it keeps the existing values. This worked as expected in SDK for IOS
7. Expected Behavior:  When clearing the Location field value should be empty when assigned null instead it keeps the existing values.  First, these Values are saved to the local soup field where it is saved as null after the soup syncs with the salesforce there are previously saved values. But when assigning an empty string it will updated as an empty string but the numerical fields show 0 when assigning an empty String. we expect when assign null to theLocation field the field should be updated as null.
This worked as expected in SDK for IOS. 
8. Error Log:  No error logs.

**Comment by wmathurin** [comment] 2023-10-23 23:26
Looks like a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/2445
Could you answer the questions I had there?

**Comment by NewTech2000** [comment] 2023-10-24 05:12
> Looks like a duplicate of #2445 Could you answer the questions I had there?

Okay

**Comment by wmathurin** [comment] 2024-03-02 01:33
Closing this issue - since it's a duplicate.

**Closed by wmathurin** 2024-03-02 01:33 UTC
