### ISSUE TITLE
Crash on Android 14 devices [One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts] 

### ISSUE THREAD

**Issue by ashish-kumar1994** [forcedotcom/SalesforceMobileSDK-Android#2530] opened 2024-03-20 09:08 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 10.2.0
2. Issue found in Native App or Hybrid App: React Native
3. OS Version: Android
4. Device: Android 14 (API 34)
5. Steps to reproduce: While running the app is not open
6. Actual behavior: Crash
7. Expected Behavior:Open the App
8. Error Log: 
at com.salesforce.androidsdk.app.SalesforceSDKManager.<init>(SalesforceSDKManager.java:273) at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.<init>(SmartStoreSDKManager.java:74) at com.salesforce.androidsdk.mobilesync.app.MobileSyncSDKManager.<init>(MobileSyncSDKManager.java:58) at com.salesforce.androidsdk.reactnative.app.SalesforceReactSDKManager.<init>(SalesforceReactSDKManager.java:66) at com.salesforce.androidsdk.reactnative.app.SalesforceReactSDKManager.init(SalesforceReactSDKManager.java:72) at com.salesforce.androidsdk.reactnative.app.SalesforceReactSDKManager.initReactNative(SalesforceReactSDKManager.java:90)

**Comment by brandonpage** [comment] 2024-03-20 15:19
Hi @ashish-kumar1994, this only happens if target/compile for API 34.  If you target API 33 the app will run without crashing on Android 14/API 34.  React Native did not backport this fix far enough to support the version we were using and we could not upgrade until a major release due to large breaking changes (Grade 8 + Java 17).  

This issue is isolated to React Native but will be fixed with the release of Mobile SDK 12.0 next month.

**Closed by brandonpage** 2024-03-20 15:19 UTC

**Comment by roshanmtx** [comment] 2024-04-22 12:11
@brandonpage can you please let me know when Mobile SDK 12.0 will be released

**Comment by mahipalsingh-syt** [comment] 2024-05-17 14:05
issue reproducible in 12.0.1: 
one of RECEIVER_EXPORTED or receiver_not_exported should be specified when a receiver isn't being registered exclusively for system broadcasts
