### ISSUE TITLE
Provide option to Remove Salesforce Mobile Developer Support Notification in Android

### ISSUE THREAD

**Issue by ukrrrish** [forcedotcom/SalesforceMobileSDK-Android#2510] opened 2024-02-06 07:02 UTC
1.Version of Mobile SDK Used: 11.1.0
2.Issue found in Native App or Hybrid App:Android Native App
5. Steps to reproduce:Login To App.
6. Actual behavior :We are getting notification on Login,which does not required on release mode 
7. Expected Behavior: Provide option to disable Salesforce Mobile Developer Support Notification.
               we tried with following approach 
                MobileSyncSDKManager.getInstance().isDevSupportEnabled = false
                
But it did not worked.could you suggest any other way to disable Salesforce Mobile Developer Support Notification.

<img width="308" alt="notification" src="https://github.com/forcedotcom/SalesforceMobileSDK-Android/assets/34389810/bdea8ed7-b26d-4c60-a527-c86352f4b72e">

**Comment by JohnsonEricAtSalesforce** [comment] 2024-02-06 17:25
[ukrrrish](https://github.com/ukrrrish), thanks for reporting this.  That isn't intended to be displayed when you've set `isDevSupportEnabled` to `false`, which is correct on your part.  I'll take a look today to see if there's a way I can reproduce this on 11.1 and provide a work-around, plus schedule a fix for the next release.

Thanks for reporting this one.

**Comment by JohnsonEricAtSalesforce** [comment] 2024-02-06 18:49
@ukrrrish - When you're depending on the Salesforce Mobile SDK libraries in your app, are you depending on them directly from the release artifacts in Maven Central? In `build.gradle.kts` (or `build.gradle`), the dependencies would look like this.
```
implementation("com.salesforce.mobilesdk:SalesforceSDK:11.1.0")
```
Note a version is specified and the `project` directive is not used.  You'd also want to disable any Gradle composite build or project include that could be building Salesforce Mobile SDK from source.  Those would appear in `settings.gradle.kts` (or `settings.gradle`) and follow a form such as this.
```
include("libs:SalesforceSDK") // Or, look for `includeProject` as that was used by older Android apps.
```

I did a test just now and it appeared the release version of the libraries on Maven Central are behaving as you expected.  Let me know if that helps.

**Comment by JohnsonEricAtSalesforce** [comment] 2024-02-13 18:37
@ukrrrish - Did the changes above solve your issue? In hoping so, I'll close this one out for now.  Reply if there's still anything we can help with.

**Closed by JohnsonEricAtSalesforce** 2024-02-13 18:37 UTC
