### ISSUE TITLE
runSync hides Exception, could not handle error(message) in Hybrid App.

### ISSUE THREAD

**Issue by rovqapint** [forcedotcom/SalesforceMobileSDK-Android#956] opened 2015-09-28 11:52 UTC
callbackContext.error(e.getMessage()) in SmartSyncPlugin is not called on Exception. SyncManager hides Exception.

```java
public class SyncManager {
    ...
    public void runSync(final SyncState sync, final SyncUpdateCallback callback) {
		updateSync(sync, SyncState.Status.RUNNING, 0, callback);
		threadPool.execute(new Runnable() {
            @Override
            public void run() {
                try {
                   ...
                } catch (Exception e) {
                    Log.e("SmartSyncManager:runSync", "Error during sync: " + sync.getId(), e);
                    // Update status to failed
                    updateSync(sync, SyncState.Status.FAILED, UNCHANGED, callback);
                }
            }
        });
	}
    ...
}

public class SmartSyncPlugin extends ForcePlugin {
@Override
    public boolean execute(String actionStr, JavaScriptPluginVersion jsVersion, final JSONArray args, final CallbackContext callbackContext) throws JSONException {
     ...
     // Not running smartstore action on the main thread
        cordova.getThreadPool().execute(new Runnable() {
            @Override
            public void run() {
                // All smart store action need to be serialized
                synchronized(SmartSyncPlugin.class) {
                    try {
                       ...
                    }
                    catch (Exception e) {
                        Log.w("SmartSyncPlugin.execute", e.getMessage(), e);
                        callbackContext.error(e.getMessage());
                    }                   
                    Log.d("SmartSyncPlugin.execute", "Total time for " + action + "->" + (System.currentTimeMillis() - start));
                }
            }
        });
        Log.d("SmartSyncPlugin.execute", "Main thread time for " + action + "->" + (System.currentTimeMillis() - start));
        return true;
    }
}
```

**Comment by wmathurin** [comment] 2015-09-28 20:37
Thanks for bringing it up. We will look into it.

**Comment by rovqapint** [comment] 2015-10-15 11:14
Any news?

**Comment by Entamut** [comment] 2015-10-23 12:41
I'm opening a related issue:
https://github.com/forcedotcom/SalesforceMobileSDK-Shared/issues/308

**Comment by huminzhi** [comment] 2016-07-20 18:37
The issue is fixed in build:MobileSDK.Android.5.0

**Closed by huminzhi** 2016-07-20 18:37 UTC
Labels: bug

**Comment by wmathurin** [comment] 2017-04-06 23:35
This is not a bug.
Look at the original code you posted.
The sync is executed on a separate thread.
The cordova call returns without waiting for it.
JavaScript events will be sent to report back the sync progress (or its failures).
For an example of code listening to such events look at https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/master/samples/smartsyncexplorer/SmartSyncExplorer.html#L147
