### ISSUE TITLE
Opening the salesforce web page not redirecting to the application after login 

### ISSUE THREAD

**Issue by as8703** [forcedotcom/SalesforceMobileSDK-Android#2170] opened 2021-03-04 05:53 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 9.0.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 8.1.0
4. Device: TC 25
5. Steps to reproduce: Stay login page on a very long time then login
6. Actual behavior: Opening the salesforce web page not redirecting to the application.
![WhatsApp Image 2021-03-04 at 8 50 27 AM](https://user-images.githubusercontent.com/18522583/109917851-07c60780-7cdc-11eb-8707-e5db8f3bd54b.jpeg)

7. Expected Behavior: After login should redirect to the application.
8. Error Log:

**Comment by wmathurin** [comment] 2021-03-04 17:39
This looks like a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/466#issuecomment-783865610.

The login flow inside the webview is a black box in the Mobile SDK and is entirely driven by the server side oauth code.
I believe the server side team is aware of the issue but it's considered low priority. I can't say when or whether it will get fixed.

**Closed by wmathurin** 2021-03-04 17:39 UTC

**Comment by AkshayLaghate** [comment] 2023-11-30 06:58
@as8703 Did you find the solution for this?
