### ISSUE TITLE
Compiling release version fails with 'Couldn't follow symbolic link' message.

### ISSUE THREAD

**Issue by daraselia** [forcedotcom/SalesforceMobileSDK-Android#1531] opened 2017-10-31 10:32 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 5.3.0
2. Issue found in Native App or Hybrid App: React native
3. OS Version: iOS 11
4. Device: iPad Air
5. Steps to reproduce:
> forcedroid create (react native)
> react-native run-android (all works so far)
> when following the steps described in this [link](https://facebook.github.io/react-native/docs/signed-apk-android.html) it fails on './gradlew assembleRelease' saying:

`Could not list contents of '/Users/ilya/Playground/test25/mobile_sdk/salesforcemobilesdk-android/hybrid/HybridSampleApps/AccountEditor/assets/www/AccountEditor.html'. Couldn't follow symbolic link.`

6. Actual behavior: error compiling release version
7. Expected Behavior: successful generation of android app apk
8. Error Log:

`Could not list contents of '/Users/ilya/Projects/booker25-touch-android/mobile_sdk/salesforcemobilesdk-android/hybrid/HybridSampleApps/AccountEditor/assets/www/AccountEditor.html'. Couldn't follow symbolic link.`

**Comment by bhariharan** [comment] 2017-10-31 16:26
Duplicate of [this issue](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/48).

**Closed by bhariharan** 2017-10-31 16:26 UTC
