### ISSUE TITLE
Android App is throwing exception "Caused by com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException User is logging out"

### ISSUE THREAD

**Issue by Deepika-PFJ** [forcedotcom/SalesforceMobileSDK-Android#2559] opened 2024-05-02 11:36 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 11.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 14
4. Device: Samsung Galaxy S22 Ultra
5. Steps to reproduce: Tap "Logout" CTA on ScreenLockActivity
6. Actual behavior: App is throwing exception "Caused by com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException User is logging out"
8. Expected Behavior: App should not crash.
9. Error Log: ```
Caused by com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException
User is logging out
com.salesforce.androidsdk.rest.ClientManager.peekRestClient (ClientManager.java:182)
com.salesforce.androidsdk.rest.ClientManager.peekRestClient (ClientManager.java:161)
com.salesforce.androidsdk.rest.ClientManager.getRestClient (ClientManager.java:138)
com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onResume (SalesforceActivityDelegate.java:86)
com.salesforce.androidsdk.ui.SalesforceActivity.onResume (SalesforceActivity.java:55)
android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1622)
```

**Comment by wmathurin** [comment] 2024-05-02 18:18
Could you try with the latest Mobile SDK (12.0) and let us know if the issue still occurs?

**Comment by Techfhil** [comment] 2024-10-02 12:53
Understanding the Issue
Error Overview:

The exception is raised when the user taps the "Logout" button on the ScreenLockActivity.
The expected behavior is for the app to log out without crashing.
Error Log Analysis:

The relevant error log indicates that the exception is thrown from the ClientManager.peekRestClient method, which is invoked during the resume of the activity:
java
Copy code
Caused by com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException
User is logging out
Device and Environment:

Mobile SDK Version: 11.0
OS Version: 14
Device: Samsung Galaxy S22 Ultra
Troubleshooting and Resolving the Issue
1. Update the Mobile SDK
Upgrade to Latest SDK:
The first suggestion from the contributor was to try upgrading to the latest Mobile SDK (12.0). It's important to keep dependencies updated, as newer versions may have bug fixes related to account management and logout procedures.
If you haven't already, update your project to use the latest version of the Salesforce Mobile SDK.
2. Analyze the Logout Flow
Review the Logout Implementation:

Investigate the code that handles the logout process. Ensure that the app correctly releases resources and clears any cached account information when the user logs out.
If there are asynchronous operations (like network requests) happening during the logout, ensure they are properly canceled before proceeding with the logout.
Check the ScreenLockActivity:

Look into the ScreenLockActivity where the logout button is located. Ensure that the onLogout method (or equivalent) correctly handles the logout without trying to access the rest client after the account has been cleared.
3. Implement Error Handling
Handle AccountInfoNotFoundException Gracefully:

Surround the getRestClient calls with error handling logic to prevent the app from crashing. For instance:

try {
    RestClient client = ClientManager.getInstance().getRestClient();
    // Use the client...
} catch (AccountInfoNotFoundException e) {
    // Handle the exception, possibly redirect to login or show a message
}
Modify onResume Method:

In SalesforceActivityDelegate.onResume, ensure that any necessary checks are performed before attempting to access the rest client. This could prevent the app from crashing if the user has logged out.
4. Test Across Different Scenarios
Testing on Multiple Devices:
After implementing the changes, test the logout functionality on various devices, especially those with different Android versions, to ensure consistent behavior.
Check for Related Issues:
Look through the issues reported on the Salesforce Mobile SDK GitHub repository to see if similar problems have been addressed by other users or contributors.

**Comment by wmathurin** [comment] 2024-10-29 23:57
Closing issue - no customer response.

**Closed by wmathurin** 2024-10-29 23:57 UTC
