### ISSUE TITLE
forcedroid create wrongfully detects Cordova 6.3.0

### ISSUE THREAD

**Issue by JimBTek** [forcedotcom/SalesforceMobileSDK-Android#1209] opened 2016-07-31 22:04 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: forcedroid version 4.2.0
2. Issue found in Native App or Hybrid App:  Creating hybrid_local
3. OS Version: Win 10
4. Device:  N/A
5. Steps to reproduce:  `npm install -g cordova`  (it installs 6.3.0 currently)  then `forcedroid create`
6. Actual behavior:  

". Should be in the format x[.y[.ignored]]
) is less than the minimum required version (5.4.0).  Please update your version of Cordova.

7. Expected Behavior:
8. Error Log:

Uninstalling Cordova then `npm install -g cordova@6.2.0`  works.  The above warning about the name not being written correctly is false because of this error.  i used  com.company.appname  and after switching to Cordova 6.2.0 and using the same exact settings my project was built

**Comment by huminzhi** [comment] 2016-08-01 19:43
@rwhitley @bhariharan a doc bug in code?

**Comment by huminzhi** [comment] 2016-08-12 16:30
@kchitalia I looked into this issue again, seems I misunderstood it... 
So looks like on Windows 10, it only works with cordova@6.2.0,  but not 6.3.0 for some reason.. Will you please try to reproduce this issue? 
If it indeed can only work with cordova 6.2.0 on Win10, we should update the doc
If it's a bug which causes this error, we should fix it....

**Comment by huminzhi** [comment] 2016-08-31 18:36
The issue is fixed or solved in latest build.

**Comment by JimBTek** [comment] 2016-08-31 18:41
Great thanks!

**Comment by huminzhi** [comment] 2016-08-31 21:15
Sorry @JimBTek , I accidentally closed it, but the issue is not fixed by us since it's a cordova issue in 6.3.0. You need to turn off a flag. @bhariharan @rwhitley Will you pease advice here. Thank you!

**Comment by JimBTek** [comment] 2016-08-31 21:17
@huminzhi oh OK. It was more an FYI to you all. I'm just learning/playing so 6.2 is fine but wanted to provide feedback to help out in case anyone else hits the same problem. Thanks!

**Comment by huminzhi** [comment] 2016-09-06 21:24
Hi, if you want to use cordova v6.3.0, you will need to "cordova telemetry off" before "forcedroid create". We will see if we can work around this issue introduced by cordova v6.3.0, or we need to update documentation. Thank you @JimBTek

**Comment by huminzhi** [comment] 2016-09-06 21:24
Hi, if you want to use cordova v6.3.0, you will need to "cordova telemetry off" before "forcedroid create". We will see if we can work around this issue introduced by cordova v6.3.0, or we need to update documentation. Thank you @JimBTek

**Comment by huminzhi** [comment] 2016-09-06 21:24
Hi, if you want to use cordova v6.3.0, you will need to "cordova telemetry off" before "forcedroid create". We will see if we can work around this issue introduced by cordova v6.3.0, or we need to update documentation. Thank you @JimBTek

**Comment by huminzhi** [comment] 2016-09-06 21:25
Hi, if you want to use cordova v6.3.0, you will need to "cordova telemetry off" before "forcedroid create". We will see if we can work around this issue introduced by cordova v6.3.0, or we need to update documentation. Thank you!

**Comment by JimBTek** [comment] 2016-09-06 21:30
ah ok, thanks for the update!

If you need me to test anything else in the future let me know.

**Comment by bhariharan** [comment] 2016-09-20 05:27
This is fixed in `unstable` and will be a part of our next release.

**Closed by bhariharan** 2016-09-20 05:27 UTC
Labels: documentation
