### ISSUE TITLE
SmartSync does not report errors with syncing

### ISSUE THREAD

**Issue by jeremyhiggs** [forcedotcom/SalesforceMobileSDK-Android#1162] opened 2016-06-14 10:32 UTC
I've been trying to figure out why the changes I made locally were not syncing with Salesforce, and discovered that there are some fields that Salesforce is rejecting (because they can't be edited). However, SmartSync was not reporting this.

Debugging SyncUpTarget.java, line 138, I found the following message:
> [{"message":"Unable to create/update fields: LastModifiedDate, Days_Open__c, Converted__c. Please check the security settings of this field and verify that it is read/write for your profile or permission set.","errorCode":"INVALID_FIELD_FOR_INSERT_UPDATE","fields":["LastModifiedDate","Days_Open__c","Converted__c"]}]

Having this output to console would be really useful, but instead the status code of the response is returned.

I also noticed that in this case, a code of 400 was returned through the rest client, but line 435 in SyncManager does not have any case for handling such an error.

**Comment by jeremyhiggs** [comment] 2016-06-14 11:51
SyncUpTarget.createOnServer also does not report errors with record creation.

**Comment by huminzhi** [comment] 2016-09-02 18:36
The issue is fixed in build:MobileSDK.Android.5.0

**Closed by huminzhi** 2016-09-02 18:36 UTC
Labels: backlog
