### ISSUE TITLE
Bug when after comes back of background if you click on the App icon 

### ISSUE THREAD

**Issue by isaac-israel-aquant** [forcedotcom/SalesforceMobileSDK-Android#2378] opened 2023-01-15 15:35 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 
v. 7.0 
2. Issue found in Native App or Hybrid App:
 At Hybrid App
3. OS Version:
   API 33
4. Device:
 Pixel 3A
6. Steps to reproduce:
  1.  Logout
  2. On the login screen put the app in the background 
  3.  Click on the app icon to open it 
8. Actual behavior:
  After login, the app does not navigate to the home screen (The screen that should appear after login )
10. Expected Behavior:
 After login, the app does navigate to the home screen

**Comment by brandonpage** [comment] 2023-01-30 21:56
Hi @isaac-israel-aquant,

Mobile SDK 7.0 is over 4 years old and this issue isn't being reported by others so it has likely been fixed within that time.  I am not able to reproduce the issue now so I highly recommend you upgrade.

**Closed by brandonpage** 2023-01-30 21:56 UTC

**Comment by isaac-israel-aquant** [comment] 2023-02-05 14:22
Hey @brandonpage Sorry I looked at the wrong place I am using  version :  10.0.0

**Comment by isaac-israel-aquant** [comment] 2023-02-13 13:02
Sure, I am using  React Native project we build the code like this 
```typescript
useEffect(() => {
    if (user || isLoggingOut) return

    const successCallback = (res: User) => {
      console.log('TCL: successCallback -> res', res)
      setUser(res)
      logger.setUserId(res.userId)
    }

    // check if logged in
    oauth.getAuthCredentials(successCallback, () => {
      // if not logged in, log in
      oauth.authenticate(successCallback, (error: any) =>
        console.log('Failed to authenticate:' + error)
      )
    })
  }, [user])
```
