### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by Nemisis** [forcedotcom/SalesforceMobileSDK-Android#868] opened 2015-04-09 18:01 UTC
I am unable to login to my account after logging in and out a few times. These are the steps to reproduce: 

 1. Log into an account. 
 2. Logout using the `SalesforceSDKManager.getInstance().logout(activity, true)` method. 
 3. Repeat steps 1 & 2 a few times 
 4. Then, suddenly, when I click "Allow", it does nothing and the screen goes white (the progress indicator does not become visible at all). 

I debugged through the code and found that in the `shouldOverrideUrlLoading()` method, it does the following: 

		@Override
        public boolean shouldOverrideUrlLoading(WebView view, String url) {
			boolean isDone = url.replace("///", "/").toLowerCase(Locale.US).startsWith(loginOptions.oauthCallbackUrl.replace("///", "/").toLowerCase(Locale.US));
            if (isDone) {
                Uri callbackUri = Uri.parse(url);
                Map<String, String> params = UriFragmentParser.parse(callbackUri);
                String error = params.get("error");
                // Did we fail?
                if (error != null) {
                    String errorDesc = params.get("error_description");
                    onAuthFlowError(error, errorDesc);
                }
                // Or succeed?
                else {
                    TokenEndpointResponse tr = new TokenEndpointResponse(params);
                    onAuthFlowComplete(tr);
                }
            }
            return isDone;
        }

When my callback URL is loaded, it successfully goes into the `isDone` if block. In `onAuthFlowComplete(tr)`, it calls `FinishAuthtask`: 

    protected void onAuthFlowComplete(TokenEndpointResponse tr) {
        FinishAuthTask t = new FinishAuthTask();
        t.execute(tr);
    }

However, the `FinishAuthTask` is never executed (the `doInBackground` method does not get called). It seems that when the process is killed/restarted, it will work. So, if I relaunch the app from my IDE it will log in. If I force close (steps below) the app, it will allow me to login. However, backing out of the app and swiping it away will not let me login. 

 1. Go into the android Settings app. 
 2. Click "Apps" 
 3. Find the app I am working on and click on it. 
 4. Click "Force Stop" 
 5. Click OK

Note: I am able to reproduce this multiple times in the app I am creating as well as the sample "Template App" packaged with the SDK.

**Comment by bhariharan** [comment] 2015-04-09 18:03
Thanks for reporting @Nemisis! I'll take a look when I get a chance.

**Comment by sivakartik** [comment] 2015-04-16 16:32
The issue occurs due to the following reasons:
In the client manager there is a method called  public RestClient peekRestClient(Account acc)

if the account is null or if the salesforcesdk manager 's isLoggingOut variable is true 

or acc != null but any other account data is null;

The question here is why does the salesforceSDK wants to create android user account it can use shared preference to save the data ,why are multiple user account required??

If we are not getting a call back from the accountManager then we are stuck with a login loop

**Comment by camflan** [comment] 2015-05-11 16:07
Any updates to fix this log in loop when we don't get an update from AccountManager?

**Comment by akhileshgupta** [comment] 2015-06-19 06:26
We do have our authentication standardized on android account manager system because of various reasons. Also, this looks like some kind of rare race conditions as we don't expect our users to continuously login-logout multiple times simultaneously.

We will continue to keep this bug open to investigate this more. We are also happy to take in a pull request if you guys can spot the root cause.

**Comment by Nemisis** [comment] 2015-06-22 12:29
> Also, this looks like some kind of rare race conditions as we don't expect our users to continuously login-logout multiple times simultaneously.

Well, I do have a question in regards to this. While I understand what you're saying about logging in and out rapidly, this still does occur when the users token gets deauthorized (for various reasons, be it the length the org has set has expired, or they reach their max device count) and needs to log back in. So, it's not limited to quick, successive logins.

**Comment by stvnhg** [comment] 2016-01-06 13:02
@Nemisis Did you ever find a fix for this? We have similar behavior. Thank you.

**Comment by congtuyenvip** [comment] 2016-01-14 06:49
@stvnhg , @Nemisis 
I and @PhamQuangThinh had found root cause for this issue, and had solution for this.

**Comment by stvnhg** [comment] 2016-01-14 07:35
@congtuyenvip Would you mind sharing it? Thank you!

**Comment by huminzhi** [comment] 2016-05-18 03:46
@congtuyenvip @stvnhg Is this still happening, may we close this issue? Thanks for advice!

**Closed** 2016-07-19 20:57 UTC
Labels: bug

**Comment by congtuyenvip** [comment] 2016-07-20 01:09
This still happening when we upgrade to version 4.1, 4.2, although that is sample app in source code.
- The lastest version only fix account manager. In previous version, some time getting null information of account from account manager. That will cause loging out and re-active authentication.
- To fix this, we have to look into LoginActivity  instance when do login flow, and encrypt - decrypt log record also.
--> We fixed it, and no longer see this issue. So @bhariharan @huminzhi   pls review and do update source code, and should close this.

Thanks & Best regards,
